POST http://localhost:3003/user/signup
Content-Type: application/json

{
    "firstName": "Diogo" ,
    "lastName": "Bomfim",
    "email": "diogo@email.com",
    "password": "12345678"
}

####
POST http://localhost:3003/user/login
Content-Type: application/json
 
{
    "email": "diogo@email.com",
    "password": "12345678"
}

####
GET http://localhost:3003/user/get-all
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6eyJpZCI6ImZiNzE3NTJkLTlmZDUtNDk5MC1iMDExLTE4OWJmMzNkM2Q0MyJ9LCJpYXQiOjE2NzQxNTU1NzcsImV4cCI6MTY3NDE3MzU3N30.yYOLl2lbZ7x6lrKOXLeB-7rXEU2Rw8b0RPpZ7nqbk5c

####
POST http://localhost:3003/workspace/create-workspace
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6eyJpZCI6ImZiNzE3NTJkLTlmZDUtNDk5MC1iMDExLTE4OWJmMzNkM2Q0MyJ9LCJpYXQiOjE2NzQxNTU1NzcsImV4cCI6MTY3NDE3MzU3N30.yYOLl2lbZ7x6lrKOXLeB-7rXEU2Rw8b0RPpZ7nqbk5c

{
    "idUser" : "fb71752d-9fd5-4990-b011-189bf33d3d43",
    "name" : "Faculdade"
}

####
GET http://localhost:3003/workspace/get-all
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6eyJpZCI6ImZiNzE3NTJkLTlmZDUtNDk5MC1iMDExLTE4OWJmMzNkM2Q0MyJ9LCJpYXQiOjE2NzQxNTU1NzcsImV4cCI6MTY3NDE3MzU3N30.yYOLl2lbZ7x6lrKOXLeB-7rXEU2Rw8b0RPpZ7nqbk5c

####
DELETE http://localhost:3003/workspace/delete-workspace/16087adb-6097-46f0-883c-cbd12308f241
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6eyJpZCI6ImZiNzE3NTJkLTlmZDUtNDk5MC1iMDExLTE4OWJmMzNkM2Q0MyJ9LCJpYXQiOjE2NzQxNTU1NzcsImV4cCI6MTY3NDE3MzU3N30.yYOLl2lbZ7x6lrKOXLeB-7rXEU2Rw8b0RPpZ7nqbk5c


####
POST http://localhost:3003/task/create-task
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6eyJpZCI6ImZiNzE3NTJkLTlmZDUtNDk5MC1iMDExLTE4OWJmMzNkM2Q0MyJ9LCJpYXQiOjE2NzQxNTU1NzcsImV4cCI6MTY3NDE3MzU3N30.yYOLl2lbZ7x6lrKOXLeB-7rXEU2Rw8b0RPpZ7nqbk5c

{
    "idUser" : "fb71752d-9fd5-4990-b011-189bf33d3d43", 
    "title" : "Estudar Port", 
    "description" : "Preciso estudar equação para a prova de matemática", 
    "idWorkspace" : "076a0589-895e-4870-b2d9-70206c86ef39", 
    "status" : "TO_DO"
}

####
GET http://localhost:3003/task/get-all
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6eyJpZCI6ImZiNzE3NTJkLTlmZDUtNDk5MC1iMDExLTE4OWJmMzNkM2Q0MyJ9LCJpYXQiOjE2NzQxNTU1NzcsImV4cCI6MTY3NDE3MzU3N30.yYOLl2lbZ7x6lrKOXLeB-7rXEU2Rw8b0RPpZ7nqbk5c

####
DELETE http://localhost:3003/task/delete-task/b9dfca55-a2bc-4124-9bcc-f9b268888703
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6eyJpZCI6ImZiNzE3NTJkLTlmZDUtNDk5MC1iMDExLTE4OWJmMzNkM2Q0MyJ9LCJpYXQiOjE2NzQxNTU1NzcsImV4cCI6MTY3NDE3MzU3N30.yYOLl2lbZ7x6lrKOXLeB-7rXEU2Rw8b0RPpZ7nqbk5c

####
PUT http://localhost:3003/task/update-task
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6eyJpZCI6ImZiNzE3NTJkLTlmZDUtNDk5MC1iMDExLTE4OWJmMzNkM2Q0MyJ9LCJpYXQiOjE2NzQxNTU1NzcsImV4cCI6MTY3NDE3MzU3N30.yYOLl2lbZ7x6lrKOXLeB-7rXEU2Rw8b0RPpZ7nqbk5c

{
    "id" : "afa37760-9c63-46ce-b4a9-a84251239158",
    "status" : "IN_PROGRESS"
}